% interface_elbow.m
% Interface gráfica adaptada para simulação do cotovelo com elo flexível

clear all;
close all;
clc;
disp('Inicializando o ambiente do cotovelo com elo flexível, por favor aguarde...');

% Interface gráfica
GRAPHIC = 1;
graphic_step = 10;
erase_mode = 'xor';
gui_name = 'Elbow Simulator with Flexible Link';

%graph_interface = figure('Unit','normalized','NextPlot','add','Visible','on',...
   %'NumberTitle','off','Position',[0. ...
   %01,0.05,0.98,0.84],'Menubar','none',...
   %'Name', gui_name,'Pointer','arrow','Color',[.95 .95 .95],...
   %'Toolbar','none','Renderer','painters');

graph_interface = figure('Units','normalized','NextPlot','add','Visible','on',...
   'NumberTitle','off','Position',[0.01 0.05 0.98 0.84],'Menubar','none',...
   'Name', gui_name,'Pointer','arrow','Color',[1 1 1],...
   'Toolbar','none','Renderer','painters');

set(0,'Current',graph_interface);

% Cria os eixos
movie_axis = axes('Units','normalized','Position',[.08 .22 .4 .7],...
   'XGrid','on','Box','on','YGrid','on','Color','w');
axis([-0.2 0.6 0.4 1.2]);

theta_axis = axes('Units','normalized','Position',[.55 .74 .4 .2],...
   'XGrid','on','Box','on','YGrid','on');
ylabel('\theta_m e \theta_l (degree)');
title(theta_axis, 'Angular Position (\theta_m and \theta_l)');

vel_axis = axes('Units','normalized','Position',[.55 .48 .4 .2],...
   'XGrid','on','Box','on','YGrid','on');
ylabel('Velocities (degrees/s)');
title(vel_axis, 'Angular Velocities');

tau_axis = axes('Units','normalized','Position',[.55 .22 .4 .2],...
   'XGrid','on','Box','on','YGrid','on');
xlabel('Time (s)'); ylabel('Torques (N·m)');
title(tau_axis, 'Applied Torques');

% Panels
msg_panel1 = uipanel('Title','PARAMETERS','FontSize',7,...
   'BackgroundColor',[0.94 0.94 0.94],'Unit','normalized',...
   'Position',[0.08,0.02,0.46,0.13]);

msg_panel3 = uipanel('Title','COMMANDS','FontSize',7,...
   'BackgroundColor',[0.94 0.94 0.94],'Unit','normalized',...
   'Position',[0.55,0.02,0.20,0.13]);

msg_panel2 = uipanel('Title','LEGENDS','FontSize',7,...
   'BackgroundColor',[0.94 0.94 0.94],'Unit','normalized',...
   'Position',[0.76,0.02,0.20,0.13]);

uicontrol('Parent', msg_panel2, ...
    'Style', 'text', ...
    'Units', 'normalized', ...
    'Position', [0.08 0.04 0.9 0.9], ...
    'BackgroundColor', [0.94 0.94 0.94], ...
    'FontSize', 9, ...
    'HorizontalAlignment', 'left', ...
    'String', {...
        'Total Time = Simulation duration (s)', ...
        'K pat/B pat = Patient impedance', ...
        'K robot/B robot = Exoskeleton impedance', ...
        'Controller = Choose control strategy', ...
        'Blue = Humerus (upper arm – fixed)', ...
        'Red = Forearm (moving segment)'});

% Entradas de parâmetro
uicontrol('Parent',msg_panel1,'Style','text','String','Total Time:',...
    'Units','normalized','Position',[0.0,0.45,0.14,0.2]);
uicontrol('Parent',msg_panel1,'Style','text','String','Simulation duration (s)',...
    'Units','normalized','Position',[0.0,0.30,0.14,0.2]);
uiTfinal = uicontrol('Parent',msg_panel1,'Style','edit','String','6',...
    'Units','normalized','Position',[0.13,0.48,0.1,0.2],'BackgroundColor','white');
%--------------------------------------------------------------------------------------
uicontrol('Parent',msg_panel1,'Style','text','String','Patient impedance',...
    'Units','normalized','Position',[0.28,0.82,0.2,0.2]);

uicontrol('Parent',msg_panel1,'Style','text','String','K pat:',...
    'Units','normalized','Position',[0.28,0.50,0.06,0.2]);

uiControlKpac = uicontrol('Parent',msg_panel1,'Style','edit','String','10',...
    'Units','normalized','Position',[0.35,0.55,0.1,0.2],'BackgroundColor','white');
%--------------------------------------------------------------------------------------
uicontrol('Parent',msg_panel1,'Style','text','String','B pat:',...
    'Units','normalized','Position',[0.28,0.30,0.06,0.2]);

uiControlBpac = uicontrol('Parent',msg_panel1,'Style','edit','String','1',...
    'Units','normalized','Position',[0.35,0.30,0.1,0.2],'BackgroundColor','white');
%--------------------------------------------------------------------------------------
uicontrol('Parent',msg_panel1,'Style','text','String','Exoskeleton impedance',...
    'Units','normalized','Position',[0.50,0.82,0.2,0.2]);

uicontrol('Parent',msg_panel1,'Style','text','String','K robot:',...
    'Units','normalized','Position',[0.50,0.50,0.06,0.2]);
uiControlKr = uicontrol('Parent',msg_panel1,'Style','edit','String','20',...
    'Units','normalized','Position',[0.58,0.55,0.1,0.2],'BackgroundColor','white');
%--------------------------------------------------------------------------------------
uicontrol('Parent',msg_panel1,'Style','text','String','B robot:',...
    'Units','normalized','Position',[0.50,0.30,0.06,0.2]);
uiControlBr = uicontrol('Parent',msg_panel1,'Style','edit','String','2',...
    'Units','normalized','Position',[0.58,0.30,0.1,0.2],'BackgroundColor','white');
%--------------------------------------------------------------------------------------
global uiControlMode

uicontrol('Parent',msg_panel1,'Style','text','String','Controller:', ...
    'Units','normalized','Position',[0.73,0.45,0.1,0.2]);

uiControlMode = uicontrol('Parent',msg_panel1,'Style','popupmenu', ...
    'String', {'PD (Non-robust)','K1','K1+K2','K1+K2+K3'}, ...
    'Units','normalized','Position',[0.84,0.48,0.13,0.2], ...
    'BackgroundColor','white');

% Botões
callStart = 'clear elbow_model; main_elbow';
uiStart = uicontrol('Parent',msg_panel3,'Style','push','Units','normalized',...
    'Position',[0.1,0.60,0.30,0.3],'String','Start',...
    'Callback',callStart,'Enable','on');

callStop = 'stop=1;';
uiStop = uicontrol('Parent',msg_panel3,'Style','togglebutton','Units','normalized',...
   'Position',[0.1, 0.20, 0.30, 0.3],'String','Stop','Callback',callStop,'Enable','on');

callReset = 'interface_elbow';
uiReset = uicontrol('Parent',msg_panel3,'Style','push','Units','normalized',...
   'Position',[0.6, 0.60, 0.30, 0.3],'String','Reset','Callback',callReset,'Enable','on');

callClose = 'close all;clear all;';
uiClose = uicontrol('Parent',msg_panel3,'Style','push','Units','normalized',...
   'Position',[0.6,0.20,0.30,0.3],'String','Close','Callback',callClose);

% Desenho inicial do braço
anim_elbow_init;